const axios = require('axios');
const schedule = require('node-schedule');

/**
 * IoT MEASUREMENT SIMULATOR - CRON JOB
 * Simulates real-time sensor data every 30 seconds
 * 
 * Features:
 * - Generates realistic fill % progression
 * - Updates 50 containers per batch
 * - Triggers alerts when fill% > 80%
 * - Publishes RabbitMQ events for maintenance alerts
 * 
 * Performance:
 * - 50 measurements per 30 seconds
 * - ~1 measurement every 0.6 seconds
 * - 2880 measurements per day per container (if always selected)
 */

class IoTMeasurementSimulator {
  constructor(containerServiceUrl = 'http://localhost:3002') {
    this.containerServiceUrl = containerServiceUrl;
    this.measurementApiUrl = 'http://localhost:3006/api/iot/measure';
    this.job = null;
    this.isRunning = false;
    this.stats = {
      totalMeasurements: 0,
      alertsTriggered: 0,
      startTime: new Date(),
    };
    
    // Track container fill levels in memory
    this.containerFillLevels = new Map();
  }

  /**
   * Initialize simulator by fetching all containers
   */
  async initialize() {
    try {
      console.log('🔌 IoT Simulator: Initializing container cache...');
      
      const response = await axios.get(
        `${this.containerServiceUrl}/api/conteneurs`,
        { timeout: 5000 }
      );
      
      // API returns { message, conteneurs: [...] } or { data: [...] }
      let containers = response.data?.conteneurs || response.data?.data || response.data;
      
      // If the response is an object with a data property, extract it
      if (containers && typeof containers === 'object' && !Array.isArray(containers) && containers.conteneurs) {
        containers = containers.conteneurs;
      }
      
      if (!Array.isArray(containers)) {
        throw new Error(`Expected array of containers, got ${typeof containers}: ${JSON.stringify(containers).substring(0, 100)}`);
      }
      
      // Initialize each container with random starting fill%
      for (const container of containers) {
        this.containerFillLevels.set(container.id, {
          currentFill: Math.random() * 50, // Start at 0-50%
          lastUpdated: new Date(),
          alertsSent: 0,
        });
      }
      
      console.log(`✓ Loaded ${containers.length} containers into simulator cache`);
      console.log(`📊 Ready to simulate real-time measurements\n`);
      
      return containers.length;
    } catch (error) {
      console.error('❌ IoT Simulator: Failed to initialize container cache:', error.message);
      throw error;
    }
  }

  /**
   * Generate realistic fill percentage progression
   * Simulates gradual filling with occasional jumps
   */
  generateFillProgression(currentFill) {
    // 80% of time: gradual increase (0.5-2% per measurement)
    if (Math.random() < 0.8) {
      return Math.min(100, currentFill + (Math.random() * 1.5 + 0.5));
    }
    
    // 15% of time: small decrease (collection happened)
    if (Math.random() < 0.15) {
      return Math.max(0, currentFill - (Math.random() * 30 + 10));
    }
    
    // 5% of time: stay same
    return currentFill;
  }

  /**
   * Generate realistic sensor readings
   */
  generateSensorReadings(fillPercentage) {
    return {
      taux_remplissage: Math.min(100, Math.max(0, fillPercentage)),
      temperature: 10 + Math.random() * 15, // 10-25°C
      batterie: Math.max(10, 80 + Math.random() * 20), // 10-100%, usually high
      signal_force: -100 + Math.floor(Math.random() * 45), // -100 to -55 dBm
    };
  }

  /**
   * Execute one batch of measurements
   */
  async executeBatch() {
    try {
      // Select 50 random containers
      const containerIds = Array.from(this.containerFillLevels.keys());
      const selectedContainers = [];
      
      for (let i = 0; i < Math.min(50, containerIds.length); i++) {
        const randomId = containerIds[Math.floor(Math.random() * containerIds.length)];
        selectedContainers.push(randomId);
      }

      let alertsThisBatch = 0;

      // Send measurement for each selected container
      for (const containerId of selectedContainers) {
        const containerStats = this.containerFillLevels.get(containerId);
        
        // Update fill level
        const newFill = this.generateFillProgression(containerStats.currentFill);
        containerStats.currentFill = newFill;
        containerStats.lastUpdated = new Date();

        // Generate sensor readings
        const readings = this.generateSensorReadings(newFill);

        // Send measurement to IoT service
        try {
          await axios.post(
            this.measurementApiUrl,
            {
              id_conteneur: containerId,
              capteur_id: `SENSOR-${containerId.substring(0, 8)}`,
              ...readings,
              notes: 'Auto-generated by IoT simulator',
            },
            { timeout: 3000 }
          );

          // Check if alert should be triggered
          if (newFill > 80 && containerStats.alertsSent < 3) {
            await this.triggerMaintenanceAlert(containerId, newFill);
            containerStats.alertsSent += 1;
            alertsThisBatch += 1;
          }

          // Reset alerts counter if fill drops below 50%
          if (newFill < 50) {
            containerStats.alertsSent = 0;
          }

          this.stats.totalMeasurements += 1;
        } catch (error) {
          console.error(`   ⚠️ Failed to send measurement for container ${containerId}:`, error.message);
        }
      }

      // Log batch summary
      const timestamp = new Date().toLocaleTimeString();
      console.log(
        `[${timestamp}] 📊 Batch: ${selectedContainers.length} measurements | ⚠️ Alerts: ${alertsThisBatch} | Total: ${this.stats.totalMeasurements}`
      );

      this.stats.alertsTriggered += alertsThisBatch;

      return { count: selectedContainers.length, alerts: alertsThisBatch };
    } catch (error) {
      console.error('❌ IoT Simulator: Batch execution error:', error.message);
    }
  }

  /**
   * Trigger maintenance alert when container is too full
   */
  async triggerMaintenanceAlert(containerId, fillLevel) {
    try {
      console.log(`   🚨 ALERT: Container ${containerId.substring(0, 8)} is at ${fillLevel.toFixed(1)}% capacity`);
      
      // Publish events to RabbitMQ for other services to react
      try {
        const EventService = require('./EventService');
        
        // Publish maintenance alert event
        await EventService.publishEvent('container.maintenance_needed', {
          id_conteneur: containerId,
          taux_remplissage: fillLevel,
          timestamp: new Date(),
          reason: 'High fill level detected by IoT sensor',
          alert_type: 'HIGH_FILL_LEVEL',
        });
        
        // Also publish measurement alert
        await EventService.publishEvent('measurement.alert', {
          id_conteneur: containerId,
          taux_remplissage: fillLevel,
          timestamp: new Date(),
          alert_type: 'HIGH_FILL_LEVEL',
        });
        
        console.log(`   ✓ Events published to RabbitMQ (maintenance_needed + measurement.alert)`);
      } catch (error) {
        console.log(`   ⚠️ Could not publish to RabbitMQ: ${error.message}`);
      }
    } catch (error) {
      console.error('   ⚠️ Failed to trigger alert:', error.message);
    }
  }

  /**
   * Start the cron job (every 30 seconds)
   */
  async start() {
    if (this.isRunning) {
      console.log('⚠️ IoT Simulator already running');
      return;
    }

    try {
      await this.initialize();
      
      // Schedule job to run every 30 seconds
      this.job = schedule.scheduleJob('*/30 * * * * *', async () => {
        await this.executeBatch();
      });

      this.isRunning = true;
      console.log('✅ IoT Measurement Simulator started');
      console.log('   ⏱️  Running every 30 seconds');
      console.log('   📊 Simulating 50 containers per batch');
      console.log('   🚨 Alerts triggered when fill% > 80%\n');

      // Execute first batch immediately
      await this.executeBatch();
    } catch (error) {
      console.error('❌ Failed to start IoT Simulator:', error.message);
      throw error;
    }
  }

  /**
   * Stop the cron job
   */
  stop() {
    if (this.job) {
      this.job.cancel();
      this.isRunning = false;
      console.log('⏹️ IoT Measurement Simulator stopped');
    }
  }

  /**
   * Get simulator statistics
   */
  getStats() {
    const uptime = new Date() - this.stats.startTime;
    const uptimeMinutes = Math.floor(uptime / 60000);
    
    return {
      isRunning: this.isRunning,
      totalMeasurements: this.stats.totalMeasurements,
      alertsTriggered: this.stats.alertsTriggered,
      uptime: `${uptimeMinutes} minutes`,
      startTime: this.stats.startTime,
      containersCached: this.containerFillLevels.size,
      averageMeasurementsPerMinute: Math.floor((this.stats.totalMeasurements / uptimeMinutes) || 0),
    };
  }
}

module.exports = IoTMeasurementSimulator;
